# Generated by Django 5.1.3 on 2024-12-02 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_carrera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrera",
            name="duracion",
        ),
        migrations.RemoveField(
            model_name="carrera",
            name="fecha_creacion",
        ),
    ]
