# Generated by Django 5.1.3 on 2024-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_remove_carrera_duracion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
