# Generated by Django 5.1.3 on 2024-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_carrera_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_proyecto", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="proyectos/"),
                ),
            ],
        ),
    ]
